/**
 * Script generation — uploaded company lists and their saved scripts.
 *
 * Files are saved by the AI agent (via the MCP server) when a user shares a
 * CSV/XLSX in chat. The web app lists files → companies (50 per page) → one
 * company's scripts. Scripts are generated by the agent service and saved here.
 *
 * Every query is scoped to req.user.id; another user's data looks like "not found".
 */

import type { Request, Response } from "express";
import { and, count, desc, eq, inArray, sql } from "drizzle-orm";
import { z } from "zod";
import {
  companyScriptsTable,
  scriptCompaniesTable,
  scriptFilesTable,
  type ScriptType,
} from "../db/schema";
import { db } from "../lib/db";

export const SCRIPT_TYPES: readonly ScriptType[] = ["cold_email", "cold_call", "linkedin"];
const INSERT_CHUNK = 1000;
const DEFAULT_PAGE_SIZE = 50;
const MAX_PAGE_SIZE = 100;
const MAX_WEBSITE_CONTENT_CHARS = 80_000;

// ── Validation ────────────────────────────────────────────────────────────────

const companyInputSchema = z.object({
  rowNumber: z.number().int().min(1),
  companyName: z.string().trim().min(1).max(255),
  website: z.string().trim().min(1).max(500),
  extraFields: z.record(z.string(), z.string().max(500)).default({}),
});

const createFileSchema = z.object({
  filename: z.string().trim().min(1).max(255),
  userInstructions: z.string().trim().max(500).optional(),
  report: z.record(z.string(), z.number()),
  companies: z.array(companyInputSchema).min(1).max(50_000),
});

const saveScriptSchema = z.object({
  status: z.enum(["ok", "insufficient_data"]),
  angle: z.enum(["website", "industry"]).default("website"),
  whatTheySell: z.string().max(2000).default(""),
  problemStatement: z.string().max(2000).default(""),
  painPoints: z.array(z.string().max(1000)).max(10).default([]),
  recommendedServices: z.array(z.string().max(100)).max(2).default([]),
  subject: z.string().max(255).optional(),
  script: z.string().max(10_000).default(""),
  wordCount: z.number().int().min(0).default(0),
  /** Optional: cache the fetched website text on the company. */
  websiteContent: z.string().max(MAX_WEBSITE_CONTENT_CHARS).optional(),
});

function userIdOf(req: Request): number | undefined {
  return req.user?.id;
}

function positiveInt(raw: unknown): number | undefined {
  const n = Number(raw);
  return Number.isInteger(n) && n > 0 ? n : undefined;
}

function isScriptType(v: unknown): v is ScriptType {
  return typeof v === "string" && (SCRIPT_TYPES as readonly string[]).includes(v);
}

function toScriptDto(row: typeof companyScriptsTable.$inferSelect) {
  return {
    type: row.type,
    status: row.status,
    angle: row.angle,
    whatTheySell: row.whatTheySell,
    problemStatement: row.problemStatement,
    painPoints: row.painPoints,
    recommendedServices: row.recommendedServices,
    subject: row.subject,
    script: row.script,
    wordCount: row.wordCount,
    updatedAt: row.updatedAt,
  };
}

// ── POST /script-files ────────────────────────────────────────────────────────

export async function createScriptFile(req: Request, res: Response) {
  try {
    const userId = userIdOf(req);
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const parsed = createFileSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ error: "Invalid script file payload", details: parsed.error.issues.slice(0, 5) });
    }
    const { filename, userInstructions, report, companies } = parsed.data;

    const file = await db.transaction(async (tx) => {
      const [created] = await tx
        .insert(scriptFilesTable)
        .values({
          userId,
          filename,
          userInstructions: userInstructions || null,
          totalRows: report.totalRows ?? companies.length,
          companyCount: companies.length,
          report,
        })
        .returning();

      for (let i = 0; i < companies.length; i += INSERT_CHUNK) {
        await tx.insert(scriptCompaniesTable).values(
          companies.slice(i, i + INSERT_CHUNK).map((c) => ({
            fileId: created!.id,
            userId,
            rowNumber: c.rowNumber,
            companyName: c.companyName,
            website: c.website,
            extraFields: c.extraFields,
          })),
        );
      }
      return created!;
    });

    return res.status(201).json({
      fileId: file.id,
      filename: file.filename,
      companyCount: file.companyCount,
      totalRows: file.totalRows,
      report: file.report,
      createdAt: file.createdAt,
    });
  } catch (err) {
    console.error("createScriptFile error:", err);
    return res.status(500).json({ error: "Could not save the file" });
  }
}

// ── GET /script-files ─────────────────────────────────────────────────────────

export async function listScriptFiles(req: Request, res: Response) {
  try {
    const userId = userIdOf(req);
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const files = await db
      .select({
        id: scriptFilesTable.id,
        filename: scriptFilesTable.filename,
        companyCount: scriptFilesTable.companyCount,
        totalRows: scriptFilesTable.totalRows,
        createdAt: scriptFilesTable.createdAt,
        scriptCount: sql<number>`count(${companyScriptsTable.id})::int`,
      })
      .from(scriptFilesTable)
      .leftJoin(scriptCompaniesTable, eq(scriptCompaniesTable.fileId, scriptFilesTable.id))
      .leftJoin(
        companyScriptsTable,
        and(eq(companyScriptsTable.companyId, scriptCompaniesTable.id), eq(companyScriptsTable.status, "ok")),
      )
      .where(eq(scriptFilesTable.userId, userId))
      .groupBy(scriptFilesTable.id)
      .orderBy(desc(scriptFilesTable.createdAt));

    return res.json({ files });
  } catch (err) {
    console.error("listScriptFiles error:", err);
    return res.status(500).json({ error: "Could not load files" });
  }
}

// ── GET /script-files/:id/companies?page&limit ────────────────────────────────

export async function listScriptCompanies(req: Request, res: Response) {
  try {
    const userId = userIdOf(req);
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const fileId = positiveInt(req.params.id);
    if (!fileId) return res.status(400).json({ error: "Invalid file id" });

    const page = positiveInt(req.query.page) ?? 1;
    const limit = Math.min(positiveInt(req.query.limit) ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE);

    const [file] = await db
      .select()
      .from(scriptFilesTable)
      .where(and(eq(scriptFilesTable.id, fileId), eq(scriptFilesTable.userId, userId)))
      .limit(1);
    if (!file) return res.status(404).json({ error: "File not found" });

    const where = and(eq(scriptCompaniesTable.fileId, fileId), eq(scriptCompaniesTable.userId, userId));
    const [[totalRow], rows] = await Promise.all([
      db.select({ total: count() }).from(scriptCompaniesTable).where(where),
      db
        .select({
          id: scriptCompaniesTable.id,
          rowNumber: scriptCompaniesTable.rowNumber,
          companyName: scriptCompaniesTable.companyName,
          website: scriptCompaniesTable.website,
        })
        .from(scriptCompaniesTable)
        .where(where)
        .orderBy(scriptCompaniesTable.rowNumber)
        .limit(limit)
        .offset((page - 1) * limit),
    ]);

    // Which script types already exist for the companies on this page.
    const ids = rows.map((r) => r.id);
    const existing = ids.length
      ? await db
          .select({ companyId: companyScriptsTable.companyId, type: companyScriptsTable.type })
          .from(companyScriptsTable)
          .where(and(inArray(companyScriptsTable.companyId, ids), eq(companyScriptsTable.status, "ok")))
      : [];
    const typesByCompany = new Map<number, ScriptType[]>();
    for (const e of existing) {
      typesByCompany.set(e.companyId, [...(typesByCompany.get(e.companyId) ?? []), e.type]);
    }

    const total = totalRow?.total ?? 0;
    return res.json({
      file: { id: file.id, filename: file.filename, companyCount: file.companyCount, report: file.report, createdAt: file.createdAt },
      items: rows.map((r) => ({ ...r, scriptTypes: typesByCompany.get(r.id) ?? [] })),
      total,
      page,
      limit,
      totalPages: Math.max(1, Math.ceil(total / limit)),
    });
  } catch (err) {
    console.error("listScriptCompanies error:", err);
    return res.status(500).json({ error: "Could not load companies" });
  }
}

// ── GET /script-companies/:id[?includeContent=true] ───────────────────────────

export async function getScriptCompany(req: Request, res: Response) {
  try {
    const userId = userIdOf(req);
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const companyId = positiveInt(req.params.id);
    if (!companyId) return res.status(400).json({ error: "Invalid company id" });

    const [row] = await db
      .select({ company: scriptCompaniesTable, file: scriptFilesTable })
      .from(scriptCompaniesTable)
      .innerJoin(scriptFilesTable, eq(scriptFilesTable.id, scriptCompaniesTable.fileId))
      .where(and(eq(scriptCompaniesTable.id, companyId), eq(scriptCompaniesTable.userId, userId)))
      .limit(1);
    if (!row) return res.status(404).json({ error: "Company not found" });

    const scripts = await db
      .select()
      .from(companyScriptsTable)
      .where(eq(companyScriptsTable.companyId, companyId));

    const includeContent = req.query.includeContent === "true";
    const { company, file } = row;
    return res.json({
      id: company.id,
      fileId: file.id,
      filename: file.filename,
      userInstructions: file.userInstructions,
      rowNumber: company.rowNumber,
      companyName: company.companyName,
      website: company.website,
      extraFields: company.extraFields,
      hasWebsiteContent: !!company.websiteContent,
      ...(includeContent ? { websiteContent: company.websiteContent } : {}),
      scripts: Object.fromEntries(scripts.map((s) => [s.type, toScriptDto(s)])),
    });
  } catch (err) {
    console.error("getScriptCompany error:", err);
    return res.status(500).json({ error: "Could not load company" });
  }
}

// ── PUT /script-companies/:id/scripts/:type ───────────────────────────────────

export async function saveCompanyScript(req: Request, res: Response) {
  try {
    const userId = userIdOf(req);
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const companyId = positiveInt(req.params.id);
    if (!companyId) return res.status(400).json({ error: "Invalid company id" });
    const type = req.params.type;
    if (!isScriptType(type)) return res.status(400).json({ error: `type must be one of ${SCRIPT_TYPES.join(", ")}` });

    const parsed = saveScriptSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ error: "Invalid script payload", details: parsed.error.issues.slice(0, 5) });
    }
    const { websiteContent, ...script } = parsed.data;

    const [company] = await db
      .select({ id: scriptCompaniesTable.id })
      .from(scriptCompaniesTable)
      .where(and(eq(scriptCompaniesTable.id, companyId), eq(scriptCompaniesTable.userId, userId)))
      .limit(1);
    if (!company) return res.status(404).json({ error: "Company not found" });

    if (websiteContent) {
      await db
        .update(scriptCompaniesTable)
        .set({ websiteContent, websiteFetchedAt: sql`now()` })
        .where(eq(scriptCompaniesTable.id, companyId));
    }

    const values = {
      ...script,
      subject: type === "cold_email" ? script.subject ?? null : null,
    };
    const [saved] = await db
      .insert(companyScriptsTable)
      .values({ companyId, userId, type, ...values })
      .onConflictDoUpdate({
        target: [companyScriptsTable.companyId, companyScriptsTable.type],
        set: { ...values, updatedAt: sql`now()` },
      })
      .returning();

    return res.json(toScriptDto(saved!));
  } catch (err) {
    console.error("saveCompanyScript error:", err);
    return res.status(500).json({ error: "Could not save script" });
  }
}

// ── DELETE /script-files/:id ──────────────────────────────────────────────────

export async function deleteScriptFile(req: Request, res: Response) {
  try {
    const userId = userIdOf(req);
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const fileId = positiveInt(req.params.id);
    if (!fileId) return res.status(400).json({ error: "Invalid file id" });

    const deleted = await db
      .delete(scriptFilesTable)
      .where(and(eq(scriptFilesTable.id, fileId), eq(scriptFilesTable.userId, userId)))
      .returning({ id: scriptFilesTable.id });
    if (deleted.length === 0) return res.status(404).json({ error: "File not found" });

    return res.json({ ok: true });
  } catch (err) {
    console.error("deleteScriptFile error:", err);
    return res.status(500).json({ error: "Could not delete file" });
  }
}
