/**
 * src/lib/planTypes.ts
 *
 * Type definitions for the multi-step planning feature.
 *
 * A "plan" is an ordered list of up to MAX_PLAN_STEPS MCP tool calls that
 * together fulfil a single user message.  Plans are generated by
 * PlannerService and executed by executePlanStep.node.
 *
 * Execution contract:
 *   - Safe steps (requiresApproval=false) run immediately in sequence.
 *   - The first risky step pauses execution and creates a PendingAction.
 *   - Steps after a risky step resume after the user confirms via the
 *     /api/agent/confirm endpoint (PlanResumptionContext carries the full plan).
 */

import type { KnownToolName } from "../types/tools.js";
import type { Intent } from "../config/intents.js";
import type { McpToolResult } from "../types/mcp.js";
import type { LLMIntentArguments } from "../schemas/llmIntent.schema.js";

/** Maximum number of steps a single plan may contain. */
export const MAX_PLAN_STEPS = 3;

// ── Plan step ─────────────────────────────────────────────────────────────────

/**
 * A single tool call within a multi-step plan.
 * Built by PlannerService; consumed by executePlanStep.node.
 */
export interface PlannedStep {
  /** 0-based position within the plan. */
  readonly stepIndex: number;
  /** The MCP tool to invoke for this step. */
  readonly toolName: KnownToolName;
  /** Resolved, sanitised arguments for the MCP call. */
  readonly toolArgs: Record<string, unknown>;
  /** The intent this step serves (for approval checks and response labels). */
  readonly intent: Intent;
  /** Human-readable description — shown in confirmation prompts. */
  readonly description: string;
  /** Whether this step requires explicit user confirmation before execution. */
  readonly requiresApproval: boolean;
}

// ── Step result ───────────────────────────────────────────────────────────────

/**
 * The outcome of executing a single plan step.
 * Accumulated in state.planResults as the plan progresses.
 */
export interface PlanStepResult {
  readonly stepIndex: number;
  readonly toolName: string;
  readonly toolArgs: Record<string, unknown>;
  readonly toolResult: McpToolResult;
  /** ISO-8601 timestamp recording when this step completed. */
  readonly executedAt: string;
}

// ── Plan resumption ───────────────────────────────────────────────────────────

/**
 * Stored inside PendingAction when a multi-step plan is paused at a risky
 * step.  PlanExecutionService.resumePlan() uses this context to complete
 * the plan after the user confirms the risky step.
 */
export interface PlanResumptionContext {
  /** The full plan, including the paused step and all subsequent steps. */
  readonly plan: PlannedStep[];
  /** Index of the step that is awaiting confirmation (the risky step). */
  readonly pausedStepIndex: number;
  /** Results from safe steps executed before the pause point. */
  readonly completedResults: PlanStepResult[];
  /** Forwarded for toolArgs resolution in steps after the confirmed step. */
  readonly llmExtractedArgs: LLMIntentArguments | undefined;
  /** Forwarded as campaignId fallback for steps after the confirmed step. */
  readonly activeCampaignId: string | undefined;
}
